name: remove-deploy-previews

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  branch-name:
    name: Format branch name string
    runs-on: ubuntu-latest
    outputs:
      lowercase: ${{ steps.string.outputs.lowercase }} # lowercase version
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.head_ref || github.ref_name }}

  check:
    name: check for available deploy previews
    outputs:
      remove_platform_preview: ${{ steps.check_files.outputs.remove_platform_preview }} # remove platform preview
      remove_calibrate_app_preview: ${{ steps.check_files.outputs.remove_calibrate_app_preview }} # remove calibrate app preview
      remove_next_platform: ${{ steps.check_files.outputs.remove_next_platform }} # next platform
      remove_docs: ${{ steps.check_files.outputs.remove_docs }} # docs

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified frontends
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt

          echo "remove_platform_preview=false" >>$GITHUB_OUTPUT
          echo "remove_calibrate_app_preview=false" >>$GITHUB_OUTPUT
          echo "remove_next_platform=false" >>$GITHUB_OUTPUT
          echo "remove_docs=false" >>$GITHUB_OUTPUT

          while IFS= read -r file
          do
            echo $file
            if [[ $file == netmanager/* ]]; then
              echo "remove_platform_preview=true" >>$GITHUB_OUTPUT
            fi

            if [[ $file == calibrate/* ]]; then
              echo "remove_calibrate_app_preview=true" >>$GITHUB_OUTPUT
            fi

            if [[ $file == platform/* ]]; then
              echo "remove_next_platform=true" >>$GITHUB_OUTPUT
            fi

            if [[ $file == docs/* ]]; then
              echo "remove_docs=true" >>$GITHUB_OUTPUT
            fi

          done < files.txt

  ### remove netmanager deploy preview ###
  remove-netmanager-preview:
    name: remove-netmanager-preview
    needs: [check, branch-name]
    if: needs.check.outputs.remove_platform_preview == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Google login
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SA_CREDENTIALS }}"

      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Delete PR deploy preview
        run: |-
          gcloud run services delete ${{ needs.branch-name.outputs.lowercase }}-netmanager-preview \
            --region=${{ secrets.REGION }} \
            --quiet

  ### remove calibrate-app deploy preview ###
  remove-calibrate-app-preview:
    name: remove-calibrate-app-preview
    needs: [check, branch-name]
    if: needs.check.outputs.remove_calibrate_app_preview == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Google login
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SA_CREDENTIALS }}"

      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Delete PR deploy preview
        run: |-
          gcloud run services delete ${{ needs.branch-name.outputs.lowercase }}-calibrate-app-preview \
            --region=${{ secrets.REGION }} \
            --quiet

  ### remove next-platform deploy preview ###
  remove-next-platform-preview:
    name: remove-next-platform-preview
    needs: [check, branch-name]
    if: needs.check.outputs.remove_next_platform == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Google login
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SA_CREDENTIALS }}"

      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Delete PR deploy preview
        run: |-
          gcloud run services delete ${{ needs.branch-name.outputs.lowercase }}-next-platform-preview \
            --region=${{ secrets.REGION }} \
            --quiet

  ### remove docs deploy preview ###
  remove-docs-preview:
    name: remove-docs-preview
    needs: [check, branch-name]
    if: needs.check.outputs.remove_docs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Google login
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SA_CREDENTIALS }}"

      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Delete PR deploy preview
        run: |-
          gcloud run services delete ${{ needs.branch-name.outputs.lowercase }}-docs-preview \
            --region=${{ secrets.REGION }} \
            --quiet
